/* auto-generated by NAPI-RS */
/* eslint-disable */
export type CsvValue =
  | { type: 'String', field0: string }
  | { type: 'Integer', field0: number }
  | { type: 'Float', field0: number }
  | { type: 'Boolean', field0: boolean }

export interface DataFrame {
  columns: Record<string, Array<CsvValue>>
  len: number
  dtypes: Record<string, DataType>
}

export declare const enum DataType {
  String = 0,
  Float = 1,
  Integer = 2,
  Boolean = 3
}

export declare function readCsv(path: string): DataFrame
