/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DataFrame {
  len: number
  constructor(columns: Record<string, ColumnData>, len: number)
  static fromColumns(columns: Record<string, ColumnData>): DataFrame
  colDtype(col: string): DataType | null
  get(col: string): ColumnData | null
  get columns(): Record<string, ColumnData>
  writeCsv(path: string): void
}

export declare function asBooleanArray(column: ColumnData): Array<boolean> | null

export declare function asFloatArray(column: ColumnData): Array<number> | null

export declare function asIntArray(column: ColumnData): Array<number> | null

export declare function asStringArray(column: ColumnData): Array<string> | null

export type ColumnData =
  | { type: 'String'; field0: Array<string> }
  | { type: 'Integer'; field0: Array<number> }
  | { type: 'Float'; field0: Array<number> }
  | { type: 'Boolean'; field0: Array<boolean> }

export declare const enum DataType {
  String = 0,
  Float = 1,
  Integer = 2,
  Boolean = 3,
}

export declare function readCsv(path: string): DataFrame

export declare function toBoolColumn(data: Array<boolean>): ColumnData

export declare function toFloatColumn(data: Array<number>): ColumnData

export declare function toIntColumn(data: Array<number>): ColumnData

export declare function toStringColumn(data: Array<string>): ColumnData
