/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DataFrame {
  len: number
  constructor(columns: Record<string, ColumnData>, len: number)
  colDtype(col: string): DataType | null
  get(col: string): ColumnData | null
  get columns(): Record<string, ColumnData>
}

export type ColumnData =
  | { type: 'String'; field0: Array<string> }
  | { type: 'Integer'; field0: Array<number> }
  | { type: 'Float'; field0: Array<number> }
  | { type: 'Boolean'; field0: Array<boolean> }

export type CsvValue =
  | { type: 'String'; field0: string }
  | { type: 'Integer'; field0: number }
  | { type: 'Float'; field0: number }
  | { type: 'Boolean'; field0: boolean }

export declare const enum DataType {
  String = 0,
  Float = 1,
  Integer = 2,
  Boolean = 3,
}

export declare function readCsv(path: string): DataFrame
